/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, Center } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh
  }
  materials: {
    [key: string]: THREE.Material
  }
}

interface FwishModelProps {
  viewType?: 'top' | 'side' | 'front';
  scale?: number;
  center?: boolean;
}

export function FwishModel({ viewType = 'front', center = true, ...props }: FwishModelProps) {
  const group = React.useRef<THREE.Group>(null)
  const { nodes } = useGLTF('/assets/fwish.glb') as unknown as GLTFResult

  useFrame(() => {
    if (group.current) {
      // Different rotation logic for different views to keep them "active"
      if (viewType === 'top') {
        group.current.rotation.z += 0.005 // Spins like a record
      } else {
        group.current.rotation.y += 0.005 // Normal horizontal spin
      }
    }
  })

  // Set initial orientation based on viewType
  const getInitialRotation = (): [number, number, number] => {
    switch (viewType) {
      case 'top': return [-Math.PI / 2, 0, 0];
      case 'side': return [0, Math.PI / 2, 0];
      case 'front': return [0, 0, 0];
      default: return [0, 0, 0];
    }
  }

  const model = (
    <mesh
      name="mesh_0"
      geometry={nodes.mesh_0.geometry}
    >
      <meshStandardMaterial
        color="#111111"
        metalness={0.9}
        roughness={0.2}
      />
    </mesh>
  );

  return (
    <group
      ref={group}
      rotation={getInitialRotation()}
      {...props}
      dispose={null}
    >
      {center ? <Center>{model}</Center> : model}
    </group>
  )
}

useGLTF.preload('/assets/fwish.glb')
